# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b3d0fa739364c1d6cb315206471d99256b58dfdfa9b256f0375b53da55de4c3b952f9b2e5b713f3309fa5ee50eff8238ef2218093ea3a4a277ced9d3f233909

test:
  secret_key_base: c07a40f24d4c294b7bb65d66fff1d999bed9c6ea2daa5f3343c51489be6a63d604f7bf2bf998c4540770b62c8d4076438dc0cb106be873368d282a026754b7f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
