# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bc62b30cf83281feb609898ec5b7785c382c2fae2f3c9cb849434876dffeaf9022975049e08cf4902e9ce901ce7e49c85225366cf85c8d87b6914e00db3bc31

test:
  secret_key_base: 15b30892e82924824f86f01ba571244546a9d0c21c6e579f18fb1d96b18843c2d7a5744bec041e64a935c64e3aed5b3d4838ed84d257cac901571ae23ec53186

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
